name: Build Installers

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        java: [ '17' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute jpackage
      run: ./gradlew clean :voxx-client:jpackage
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Voxx-${{ matrix.os }}
        path: voxx-client/build/jpackage/*.dmg
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Voxx-${{ matrix.os }}
        path: voxx-client/build/jpackage/*.msi        
